version: "3.8"
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_integration"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "userpwd"
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge