version: "3.9"
services:
  Jenkins:
    image: jenkins/jenkins
    ports:
      - "8085:8080"
    links:
      - alumnos
    volumes:
      - ./Jenkins-data:/var/jenkins_home
    networks:
      mysql_network:
        aliases:
          - sql_host
  websities:
    build: .
    ports:
      - "80:80"
    links:
      - alumnos
    volumes:
      - .:/var/www
    networks:
      mysql_network:
        aliases:
          - sql_host
  go-services:
    image: golang
    links:
      - alumnos  
    networks:
      mysql_network:
        aliases:
          - sql_host
  alumnos:
    image: postgres:15
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    networks:
      mysql_network:
        aliases:
          - sql_host
volumes:
  postgres-data:

networks:
  mysql_network:
    name: sql_net
    driver: bridge